### PR TITLE
Enumerable Methods

### PR DESCRIPTION
**Pull request by thneves**
We created a our own enumerable methods in Ruby. 
- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__I must say, you've done an amazing job so far.__
- Your GitFlow is okay :+1: 
- Your linters are green :green_circle: 
- You have a very clear and well-arranged readme :100: 

__However, you need to make some changes before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] For `my_all?`
- I'm getting this error: `ArgumentError: wrong number of arguments (given 0, expected 1)` when no block/argument is given. You should make your `arg` optional by setting it to nil. (i.e. arg = nil) in the function definition. This means that your function should check for when the `arg` is given or not, and take care of both situations.
- You can use [this](https://apidock.com/ruby/v2_5_5/Enumerable/all%3F) as a reference.
- You can also check out the doc [here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F)

-  `[1, 2i, 3.14].my_all?(Numeric)` returns false, while `[1, 2i, 3.14].all?(Numeric) returns `true`. This might be a bit confusing because to humans, 2i does not look like a numeric value, but to the compiler, 2i is a numeric value (complex number). Kindly fix it so that the output is the same in both cases (true in this case).

- If `words = %w[dog door rod blade]`, `words.all?(/o/)` returns false but `words.my_all?(/o/)` returns true. when a Regex is passed as an argument, it should return false if any of the collection does not match the Regex

- if `arr = [2, 3, 1, 6, 2, 6, 4, 8, 1, 8]`, `arr.all?(3)` returns false, while `arr.my_all?(3)` returns true. Remem

- [x] For `my_any?`

- If `f_array = [nil, false, nil, false]`, `f_array.any?` returns true, while `f_array.my_any?` returns false. When no block or argument is given, #any? returns false if at least one of the collection is not true.

- When a class is passed as an argument, #any? returns true if at least one of the collections is a member of such class. e.g.
if `arr = [2, 3, 1, 6, 2, 6, 4, 8, 1, 8]`, then `arr.any?(Numeric)` returns true, while `arr.my_any?(Numeric)` returns something else.

- When a Regex is passed as an argument, #any? returns true if any of the collection matches the Regex. e.g. 
If `words = %w[dog door rod blade]`, then `words.any?(/d/)` returns true, while `words.my_any?(/d/)` returns false.

- When a pattern other than Regex or a Class is given, #any? returns true if any of the collection matches the pattern. e.g.
Given `words = %w[cat door rod blade]`, `words.any?('cat')` returns true, but `words.my_any?('cat') returns false.

- [ ] For `my_none?`

- When a Regex is passed as an argument returns true if none of the collection matches the Regex. For instance,
Given `words = %w[dog door rod blade]`, `words.none?(/z/)` returns true, but `words.my_none?(/z/)` returns false.

- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern. For instance, 
Given `words = %w[dog door rod blade]`, `words.none?(5)` returns true, but `words.my_none?(5)` returns false.

- [ ] For `#my_inject`

- Given `arr = [2, 3, 1, 6, 2, 6, 4, 8, 1, 8]`, `arr.inject` throws a `LocalJumpError` but `arr.my_inject` does not throw any error.

- Check for more details [here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject) and [here](https://apidock.com/ruby/Enumerable/inject)

- [ ] For `multiply_els`, this looks good, but you should move it outside the module: it's not part of the enumerables, it's just an extension.


**[ COMMENTS ]**
- This project looks promising, you just have to take care of some edge cases and you should be fine. 
- The enumerable module as a whole can be accessed [here](https://ruby-doc.org/core-2.6.5/Enumerable.html)

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: :construction: Invalid :construction: :rotating_light: 

## :wave: :wave: Hello @thneves and @jcy2704  . Thanks for submitting you project!

The code was submitted for as the "Testing... your enumerables" project. Please submit for a new re-review. 

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] Issues link takes to another project issues page in README

- [x] Live preview is not updated with the latest changes. To always have the latest changes connect replit with the Github account and connect the repository.

- [ ] ```my_any?``` is not passing all test cases. Should return ```false``` when no argument or no block is given and none of the elements in the collections are true.
Example:
```
[false, nil, false].any?    # false
[false, nil, false].my_any? # true
```

- [ ] ```my_inject``` is not passing all test cases. Some changes made to the code create other bugs.
- When ```inject``` when not given any block it throws an error message: ```LocalJumpError```. The issue now is that every time it doesn't have the block it raises the error. I've tested the method previously and it worked, except for the raising_error.

- [ ] ```multiply_els``` is failing because of the error above. Inside the method, the ```my_inject`` is being called but because is passed without a block is raising an error.

### [OPTIONAL]  :yellow_circle:  

- [ ] It's preferred to use a ```while``` loop than a ```for``` loop. ```while``` is improved for performance. And the ```Style/for``` cop can be enabled.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hi team :wave:

__I admire your determination to get this project done. Bear it in mind that we have to run your module through a series of test cases and we must ensure that all the test cases are passed. Please check my review feedback blow:__

**[ REQUIRED CHANGES ]**

_Please be cautious while making these changes so as not to lead to other bugs._

- [x] `my_each` is not passing all the test cases. 
- This is caused because when we call `my_each` on a range, it returns an error `NameError: undefined local variable or method 'length' for 5..50: Range` This means that the `length` function is only applicable to arrays but not range. Kindly fix this.
- This error is also applicable to `my_each_with_index`, `my_select`, `my_none?`, `my_count`, `my_inject` and  `my_all`. Whenever these methods are called on `Range` of values, the above error is returned.

```
arr = [1,2,3]
arr.my_each { |num| p num + arr.length }  # 4, 5, 6

range = [1..3]
range.my_each { |num| p num + range.length } # returns error
```

- [x] When a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern. 

```
words = %w[cat door rod blade]
p words.any?('cat') # true

p words.my_any?('cat') # false
```

- [x] `my_inject` is not passing all test cases. When a symbol is specified without an initial value, `inject` combines each element of the collection by applying the symbol as a named method.

```
arr = [1,2,3,5,2,9,7]
p arr.inject(:+) # returns 29
p arr.my_inject(:+) # returns  NoMethodError: undefined method `+' for :+:Symbol
```



**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] ```my_each``` and ```my_each_with_index``` when a Range and Block is given the returned value should be the Range itself. Right now the value returned is an array with the elements in the range. Example
```
(1..5).each { |num| num } # (1..5)
(1..5).my_each { |num| num } # [1, 2, 3, 4, 5]
````
```(1..5)``` is not the same as ```[1, 2, 3, 4, 5]```

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by jubaan — APPROVED** [review]
# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

#### :clap: :clap: Great job :hammer_and_pick:!! There are no more issues left to be addressed. 

## You may now merge to master! :+1: :100:

## See you at the top :rocket:!

# :tada: :tada: :tada: :rotating_light: Status: Approved :rotating_light:  :tada: :tada: :tada:

**Pull request merged**
